from enum import Enum


class LoggerTypes(Enum):
    DEBUG = 'DEBUG'
    ACTIONS = 'ACTIONS'
    AGENT_TO_ENV_MESSAGE = 'AGENT_TO_ENV_MESSAGE'
    ENV_TO_AGENT_MESSAGE = 'ENV_TO_AGENT_MESSAGE'
    AGENT_TO_AGENT_MESSAGE = 'AGENT_TO_AGENT_MESSAGE'
    INTERNAL_MESSAGE = 'INTERNAL_MESSAGE'
    STATE = 'STATE'
    RESULTS = 'RESULTS'